### ISSUE TITLE
The project doesn't compile in Clang in Visual studio

### ISSUE THREAD

**Issue by TheNicker** [RedSpah/xxhash_cpp#13]

**Comment by TheNicker** [comment]
Please refer to:
[include/xxhash.hpp#L159](https://github.com/RedSpah/xxhash_cpp/blob/master/include/xxhash.hpp#L159)

Possible fix: should declare __m256i only when AVX is enabled by the compiler.
```
#if XXH_VECTOR == 2
		template <>
		struct vec_type<256>
		{
			using type = __m256i;
		};
#endif
```
Please note that the above code will not work as-is, some code restructuring is needed.

**Comment by RedSpah** [comment]
Moved the use of the types `__m256i` and `__m128i` to the `intrin` namespace, guarded behind ifdef blocks. This should hopefully fix the issue.
