### ISSUE TITLE
Update for xxHash 0.7.4

### ISSUE THREAD

**Issue by saleyn** [RedSpah/xxhash_cpp#14]
This version is slightly behind the head version of xxHash.  Are you planning to update?

**Comment by RedSpah** [comment]
Just checked the source code of xxHash and indeed, dev and master seems to be at 0.7.4.

However, the repo doesn't have a 0.7.4 tag yet, or a 0.7.4 release- until that is finalized I'll wait with implementing any changes lest they're unstable or bugged.

**Comment by RedSpah** [comment]
Updated to 0.8.1. Closing.
