### ISSUE TITLE
Support for macos arm64

### ISSUE THREAD

**Issue by peter-urban** [RedSpah/xxhash_cpp#33]
Hello,

When trying to use this library on macos with clan on arm64, I get the following error: 
``/Applications/Xcode_14.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/clang/14.0.0/include/immintrin.h:14:2: error: "This header is only meant to be used on x86 and x64 architecture"``

The issue seems to be caused simply by importing immintrin.h.
Is there a known workaround for this problem?

Best
Peter

**Comment by RedSpah** [comment]
Hello,

This port doesn't explicitly support ARM platforms. It *should* work if you 

`#define XXH_VECTOR 0`

before including the `xxhash.hpp` header, and if you comment the `immintrin.h` include out of the `xxhash.hpp` header, but I can't guarantee it and don't really support it. There's always the more portable C implementation-

https://github.com/Cyan4973/xxHash

**Comment by peter-urban** [comment]
Thanks for the information and the code suggestions!
