### ISSUE TITLE
Support XXH3 ?

### ISSUE THREAD

**Issue by AlGrenadine** [RedSpah/xxhash_cpp#36]
Would be great :) :  
See https://xxhash.com/

**Comment by RedSpah** [comment]
...this library already supports xxh3.

[https://github.com/RedSpah/xxhash_cpp/blob/master/include/xxhash.hpp#L1702](https://github.com/RedSpah/xxhash_cpp/blob/master/include/xxhash.hpp#L1702)

**Comment by AlGrenadine** [comment]
Excellent, i didn't see it in the readme so i thought it wasn't there,
thanks
