### ISSUE TITLE
Make in the root dir does not work & folder structure

### ISSUE THREAD

**Issue by Flamefire** [RedSpah/xxhash_cpp#6]
It seems the makefile in the project root is a copy of the real makefile in the subfolder. Issuing `make` in the root folder results in an error as the files are not found.

In fixing this I'd suggest to reorganize the folder structure. A common way to use 3rd party libraries is by including them as a git submodule and adding their `include` folder to `-I`. With the current structure this will bring in Catch and a couple source files which may be a problem.

From what I understand it is enough to include `xxhash.hpp` into an application and it will work. None of the other files are required for consumers. Is this correct?

If so I suggest to create a folder `include` in the root containing only `xxhash.hpp` and a folder `test` (or `tests`) containing the rest. The top-level makefile will just include/redirect/... (I'm not familiar with Makefiles TBH) the tests makefile.

Thank you :)

**Comment by RedSpah** [comment]
The weird folder structure is a result of the library being developed in Visual Studio, which stores all project files in the same folder which isn't the root folder, which doesn't interact well with CI when the makefile is outside the root folder. My workaround was to add a post build event that copies the `makefile` and `.travis.yml` files from the inner folder to the root, allowing it to work seamlessly with travis.

I'm admittedly very inexperienced as far as developing actual libraries used and I don't know how to work around that in Visual Studio short of just adding more post build events to create the relevant folders and move files around.

I'm open to any help on that issue.

**Comment by Flamefire** [comment]
Did you consider using CMake?

I know it might be overkill for a header-only lib, but it can easily be made in such a way that it can be consumed by projects using cmake and this as a submodule.

I can help with that as I'm quite experienced with cmake. My solution would be:

- adapt the folder structure according to the above suggestion (include, test, examples)
- add basic CMake files requiring CMake 3.8 (my default version as it has all required parts for "modern CMake")
- (opt) add install commands, although I'd simply say: Use as submodule or copy the header. Your choice though.
- remove the VS files (can be generated by CMake)

> Visual Studio, which stores all project files in the same folder which isn't the root folder

This is the default and unfortunate for portability. What I use is:
- Generate VS project with CMake
- New files added with specified location (by default it will add them in the build folder -.-)
- Add new source files back to cmakelists
- Rebuild will rerun cmake first so errors will be obvious.

**Comment by RedSpah** [comment]
There is now a proper `makefile` in the root directory that will work on its own, as well as separate `test` and `include` folders with all the files necessary to compile the tests and just the `xxhash.hpp` header respectively.

In addition I've attempted to fix the broken `CMakeLists.txt`, guided by a very helpful tutorial (https://dominikberner.ch/cmake-interface-lib/), but sadly I'm unsure if it works in its current state as I do not myself use it.

**Comment by Flamefire** [comment]
I took a shot to switch this to CMake completely removing the need to maintain 3 build systems. Check the changed travis.yml in #12 on how to use it (basically: `cmake -DCMAKE_BUILD_TYPE=Release .. && make`)

I also fixed 1 bug in the CMakeLists and added the tests.
