### ISSUE TITLE
Make warning free build

### ISSUE THREAD

**Issue by Flamefire** [RedSpah/xxhash_cpp#7]
Compiling the current source throws a couple warnings (g++-6:
- -Wunknown-pragma
- -Wattributes
- -Wunused-parameter
- -Wsign-compare
- -Wpedantic

I suggest to build with `-Werror` on CI and take care of the warnings

**Comment by RedSpah** [comment]
The only warning originating from `xxhash.hpp` directly is `-Wunused-parameter`, and it originated from a way to work around C++14 lack of `constexpr if`. There does exist an `[[maybe_unused]]` paramenter, but sadly it itself is a C++17 feature. Unsure how to solve this issue. I can fix warnings in the test itself, but of course the header itself takes preference.

**Comment by Flamefire** [comment]
I can have a look at those warnings when I'm back on my Linux machine if you like and willing to add `-Werror` to CI.

**Comment by RedSpah** [comment]
With recent changes and cleanup I'm happy to report that the library now compiles without any warnings with `-Wall -Wextra -Wpedantic`, and clang-exclusive `-Wmost`.
